<?php
header('Content-disposition: attachment; filename='.$_GET["id"].'.pdf');
header('Content-type: application/pdf');
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B',10);
$url=base_url();
$INC_DIR = $url."img/";
$pdf->Image($INC_DIR.'logo.png',10,6,40);
//$pdf->Image('img/logo.png',10,6,40);
$pdf->SetFont('Arial','B',15);
$pdf->Cell(80,20);
$pdf->Cell(30,8,"Gracias por preferirnos",0,0,'C');
$pdf->SetY(35);
$pdf->SetFont('Arial','B',10);
$pdf->Cell(189,8,utf8_decode('De acuerdo a su solicitud, a continuación le presentamos su propuesta.'),0,1,'L');
$pdf->Ln(3);
$pdf->Cell(189,8,utf8_decode('Propuesto asegurado: '.$_GET['nombre']),1,1,'L');
$pdf->Cell(189,8,utf8_decode('Teléfono: '.$_GET['telefono']),1,1,'L');
$pdf->Cell(189,8,utf8_decode('Celular:'),1,1,'L');
//$pdf->Cell(189,8,utf8_decode('Celular: '.$_GET['celular']),1,1,'L');
$pdf->Cell(189,8,utf8_decode('Correo Electrónico: '.$_GET['email']),1,1,'L');
$pdf->Cell(189,8,utf8_decode('Cédula: '.$_GET['cedula']),1,1,'L');
$pdf->Ln(3);
$pdf->Cell(189,8,utf8_decode('Compañía de seguros: '.$_GET['company']),1,1,'L');
$pdf->Ln(3);
$pdf->SetTextColor(255,0,0);
$pdf->Cell(59,8,utf8_decode("Cotización No.: ".$_GET['id'].""),1,0,'C');
$pdf->SetTextColor(0,0,0);
$pdf->Cell(65,8,utf8_decode('Ramo: Vida'),1,0,'C');
$pdf->Cell(65,8,utf8_decode("Fecha: ".$_GET['fecha_solicitud'].""),1,1,'C');
$pdf->Ln(3);
$pdf->SetTextColor(0,102,204);
$pdf->Cell(189,8,utf8_decode('Generales del Asegurado'),1,1,'C');
$pdf->SetTextColor(0,0,0);
$pdf->Cell(63,8,utf8_decode('Fecha de nacimiento'),1,0,'C');
$pdf->Cell(63,8,utf8_decode('Fumador'),1,0,'C');
$pdf->Cell(63,8,utf8_decode('Genero'),1,1,'C');
$pdf->Cell(63,8,utf8_decode($_GET['fecha_nac']),1,0,'C');
$pdf->Cell(63,8,utf8_decode($mensaje_fumador),1,0,'C');
$pdf->Cell(63,8,utf8_decode($sexo),1,1,'C');
$pdf->Ln(3);
$pdf->SetTextColor(0,102,204);
$pdf->Cell(189,8,utf8_decode('Coberturas, Límites y Término máximo de cobertura'),1,1,'C');
$pdf->SetTextColor(0,0,0);
$pdf->Cell(63,8,utf8_decode('Cobertura principal:'),1,0,'C');
$pdf->Cell(63,8,utf8_decode('Suma asegurada'),1,0,'C');
$pdf->Cell(63,8,utf8_decode('Término máximo de cobertura'),1,1,'C');
$pdf->Cell(63,8,utf8_decode('Muerte por cualquier causa'),1,0,'C');
$pdf->Cell(63,8,utf8_decode("B/. ".number_format($_GET['suma_asegurada'], "2", ".", ",").""),1,0,'C');
$pdf->Cell(63,8,utf8_decode($_GET['termino']),1,1,'C');
$pdf->Cell(189,8,utf8_decode('Otras coberturas: No aplica'),1,1,'C');
$pdf->Ln(3);
$pdf->SetTextColor(0,102,204);
$pdf->Cell(0,8,utf8_decode('Generales del Pago de la Prima'),1,1,'C');
$pdf->SetTextColor(0,0,0);
$pdf->Cell(63,8,utf8_decode('Frecuencia de pago'),1,0,'C');
$pdf->Cell(63,8,utf8_decode('Forma de pago'),1,0,'C');
$pdf->Cell(63,8,utf8_decode('Prima'),1,1,'C');
$pdf->Cell(63,8,utf8_decode($mensaje_frecuencia_pago),1,0,'C');
$pdf->Cell(63,8,utf8_decode($_GET['formadepago']),1,0,'C');
$pdf->Cell(63,8,utf8_decode("B/. ".number_format($_GET['poliza'], "2", ".", ",").""),1,1,'C');
$pdf->Ln(5);
$pdf->SetFillColor(255,0,0);
$pdf->Cell(189,8,("PROPUESTA VALIDA POR 7 DIAS"),1,1,'C',true);
$pdf->SetTextColor(0,0,0);
$pdf->Cell(189,8,utf8_decode('Para la pronta emisión de su póliza necesitamos nos presente los siguiente documentos:'),0,1,'C');
$pdf->Cell(189,8,utf8_decode('1. Formulario Conozca su cliente'),1,1,'L');
$pdf->Cell(189,8,utf8_decode('2. Fotocopia de Cédula del Asegurado y Contratante'),1,1,'L');
$pdf->Cell(189,8,utf8_decode('3. Solicitud de Póliza (Será entregada a usted por un ejecutivo nuestro)'),1,1,'L');
$pdf->Cell(189,8,utf8_decode('4. Formulario de descuento (Será entregada a usted por un ejecutivo nuestro)'),1,1,'L');
$pdf->Ln(3);
$pdf->Cell(189,8,utf8_decode('Llámenos al: 227-7777'),0,1,'L');
$pdf->Cell(189,8,utf8_decode('Escríbanos a: info@seguroteconviene.com'),0,1,'L');
$pdf->Output('solicitudes/'.$_GET["id"].'.pdf', 'D');
$doc = $pdf->Output('solicitudes/'.$_GET["id"].'.pdf', 'S');



?>